# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: postgres 
  # password: postgres
  username: rubygems 
  password: rubygems

development:
  <<: *default
  database: ruby_gems_bootcamp_development

test:
  <<: *default
  database: ruby_gems_bootcamp_test

production:
  <<: *default
  database: ruby_gems_bootcamp_production
  username: ruby_gems_bootcamp
  password: <%= ENV['RUBY_GEMS_BOOTCAMP_DATABASE_PASSWORD'] %>
